// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0b9OTmacJ7UOdJCJPR2xEtwLqOcuLJ0',
    appId: '1:379002763174:web:469367a7547e5b485f8167',
    messagingSenderId: '379002763174',
    projectId: 'raaheroshan-3ec41',
    authDomain: 'raaheroshan-3ec41.firebaseapp.com',
    storageBucket: 'raaheroshan-3ec41.appspot.com',
    measurementId: 'G-PJK0379C5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ySAnmt6bkmebtxSBgGHsHjm1IWMndH8',
    appId: '1:379002763174:android:f52e8ec300802dce5f8167',
    messagingSenderId: '379002763174',
    projectId: 'raaheroshan-3ec41',
    storageBucket: 'raaheroshan-3ec41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDZHugupPVJTvtrUVvJLlUgjTYoFhWcg',
    appId: '1:379002763174:ios:8c350fba81c1e7535f8167',
    messagingSenderId: '379002763174',
    projectId: 'raaheroshan-3ec41',
    storageBucket: 'raaheroshan-3ec41.appspot.com',
    iosClientId: '379002763174-fn726offpa0dv08f1rp1bpp72n5en3p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.raahERoshan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlDZHugupPVJTvtrUVvJLlUgjTYoFhWcg',
    appId: '1:379002763174:ios:bc81195d3b3cf54c5f8167',
    messagingSenderId: '379002763174',
    projectId: 'raaheroshan-3ec41',
    storageBucket: 'raaheroshan-3ec41.appspot.com',
    iosClientId: '379002763174-4hrcc0lj7jt3u84efdstdsfa0ju9vd1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.raahERoshan.RunnerTests',
  );
}
